{% set name = "nionswift-tool" %}
{% set version = "0.4.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nion-software/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 7744480c70654593d0560e46bab3005d8be02ba4e9627a91785a3490c29f9410
  patches:
    - patches/0001-Find-windeployqt-in-proper-location.patch
    - patches/0002-macOS-x86-only-and-macosdeployqt.patch

build:
  number: 2
  skip: true  # [py2k or python_impl == 'pypy']
  entry_points:
    - nionswift-tool = nion.nionswift_tool.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt6-main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - chrpath  # [linux]
    - cmake
    - make  # [not win]
    - python                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - numpy 1.22.*                          # [build_platform != target_platform]
    - qt6-main >=6.4.0,<7.0.0               # [build_platform != target_platform]
  host:
    - python
    - numpy 1.22.*
    - qt6-main >=6.4.0,<7.0.0
    - packaging
    - pip
    - setuptools
    - wheel
    - xorg-libxfixes  # [linux]
  run:
    - python
    - qt6-main >=6.4.0,<7.0.0
    - numpy >=1.21,<2.0

test:
  source_files:
    - nionui_app_test
  requires:
    - pip
    - nionswift
    - numpy
    - scipy
    - h5py
  commands:
    - test -f "$PREFIX/bin/nionswift-tool"  # [osx]
    - test -f "$PREFIX/bin/Nion Swift.app/Contents/MacOS/Nion Swift"  # [osx]
    - test -f "$PREFIX/bin/Nion Swift.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/nionswift-tool"  # [linux]
    - test -f "$PREFIX/bin/NionSwiftLauncher/NionSwiftLauncher"  # [linux]
    - test -f "$PREFIX/bin/NionSwiftLauncher/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\nionswift-tool.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionSwiftLauncher\\NionSwift.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionSwiftLauncher\\bootstrap.py" exit 1  # [win]
    - /usr/bin/sudo -n yum install -y xorg-x11-server-Xvfb  # [linux]
    - python -m pip install nionui_app_test/
    - nionswift --app nionui_app.test_ack | grep ACK  # [osx]
    - nionswift --app nionui_app.test_ack | findstr /c:"ACK"  # [win]
    - xvfb-run nionswift --app nionui_app.test_ack | grep ACK  # [linux]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: A native launcher for Nion Swift.
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
