{% set name = "nionswift-tool" %}
{% set version = "0.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nion-software/{{ name }}/archive/{{ version }}.tar.gz
  sha256: dc91eae179d4bbbe1c5a7f40219646aa7bf84d84c0a21db54c3c91eaaaa72b92

build:
  number: 0
  skip: true  # [py2k or python_impl == 'pypy']
  entry_points:
    - nionswift-tool = nion.nionswift_tool.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - chrpath  # [linux]
    - cmake
    - make  # [not win]
    - python
    - numpy 1.22.*
    - qt <6.0.0
    - packaging
    - pip
    - setuptools
    - wheel
    - xorg-libxfixes  # [linux]
  run:
    - python

test:
  commands:
    - test -f "$PREFIX/bin/nionswift-tool"  # [osx]
    - test -f "$PREFIX/bin/Nion Swift.app/Contents/MacOS/Nion Swift"  # [osx]
    - test -f "$PREFIX/bin/Nion Swift.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/nionswift-tool"  # [linux]
    - test -f "$PREFIX/bin/NionSwiftLauncher/NionSwiftLauncher"  # [linux]
    - test -f "$PREFIX/bin/NionSwiftLauncher/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\nionswift-tool.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionSwiftLauncher\\NionSwift.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionSwiftLauncher\\bootstrap.py" exit 1  # [win]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: A native launcher for Nion Swift.
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
